version: '3.4'

services:
  imageserver:
    image: imageserver
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
